#Demo: Hello World

#Python Functions = Python Objects

In Python, functions are first-class objects. This means that functions can be passed around and used as arguments, just like any other object (string, int, float, list, and so on). Consider the following three functions:


In [51]:
def say_namaste(name):
    return f"Namaste {name}"

def say_hello(name):
    return f"Hello {name}"

def greet(greeter_func,name):
    return greeter_func(name)

What is the output of the following?

In [53]:
greet(say_hello,"Bob")

'Hello Bob'

In [55]:
greet(say_namaste,"Bob")

'Namaste Bob'

## You can define a function inside a function !

In [56]:
def parent():
    print("Printing from the parent() function")

    def first_child():
        print("Printing from the first_child() function")

    def second_child():
        print("Printing from the second_child() function")

    second_child()
    first_child()

In [57]:
parent()

Printing from the parent() function
Printing from the second_child() function
Printing from the first_child() function


# Decorators
Main job: decorating a normal function i.e expanding that function's functionality 

In [58]:
def say_namaste():
    print("Namaste!")
say_namaste()

Namaste!


In [17]:
def my_decorator(func):
    def wrapper():
        print("Something is happening before the function is called.")
        func()
        print("Something is happening after the function is called.")
    return wrapper

In [59]:
say_namaste = my_decorator(say_namaste)
say_namaste()

Something is happening before the function is called.
Namaste!
Something is happening after the function is called.


What happened here? the say_namaste functions' behavior got modified by the decorator

## Example: Unlocking the door for team saathi

First lets create a function that unlocks the door

In [60]:
def unlock_door():
    print("The door has been unlocked!")
unlock_door()

The door has been unlocked!


Suppose we want to allow only team sathi without changing the unlock_door function itself

In [63]:
global person_at_door

In [20]:
def only_team_saathi(func):
    team_saathi_members = ["phurkima","divya","neha","sampada","arsana","divya","meena","utsabi","paridhi","kajal","rinky","rachana"]
    def wrapper():
      if person_at_door in team_saathi_members:
          func()
      else:
          print("Intruder alert !") 
    return wrapper

In [62]:
person_at_door = "bob"
unlock_door = only_team_saathi(unlock_door)
unlock_door()

The door has been unlocked!


*A more beautiful way to decorate*

In [64]:
@only_team_saathi
def unlock_door():
    print("The door has been unlocked!")

unlock_door()

The door has been unlocked!


**Exercise**: 

*   Learn how to pass  passing arguments to decorators
*   Learn how to return values from a decorated function

For guidance, follow this tutorial: https://realpython.com/primer-on-python-decorators/ 

# \*\*Kwargs and \*args

Magic variables that are useful when you don't know how many parameters will be passed to your function, args should always be at the end

In [67]:
def print_member_names(team_name,*args):
    print("team name:", team_name)
    print("members:")
    for item in args:
        print(item)

print_member_names("Team Saathi","Neha","Sampada","Rijesh")

team name: Team Saathi
members:
Neha
Sampada
Rijesh


Question: Guess what data type the **args** variable above is ?

In [69]:
def print_member_names(team_name, **kwargs):
    print("team name:", team_name)
    for key,value in kwargs.items():
        print(key,":",value)

print_member_names("Team Saathi",mentors=["Rijesh","Swornim","Sheetal"])

team name: Team Saathi
mentors : ['Rijesh', 'Swornim', 'Sheetal']


In [70]:
print_member_names("Team Saathi",interns=["Neha","Sampada"])

team name: Team Saathi
interns : ['Neha', 'Sampada']


Question: Guess what data type the **kwargs** variable above is ?




Note: using the specific variable names "kwargs" and "args" when using magic variables is only a convention, the real indicators of such variables is the "*" or "**" before the variable name

Want to learn more ? Look here https://book.pythontips.com/en/latest/args_and_kwargs.html

#Object-Oriented Programming in Python

### Class Declaration

Lets make a class that contains information about team saathi members

In [71]:
class TeamSaathiMembers:
  pass

In [72]:
kriti=TeamSaathiMembers()

The above class is pretty useless. Lets define some attributes

In [86]:
class TeamSaathiMembers:
  project = "Project Saathi"
  def __init__(self, name, city,specialization):
    self.name = name
    self.city = city
    self.specialization = specialization

In [74]:
TeamSaathiMembers.project

'Project Saathi'

In [75]:
TeamSaathiMembers.name

AttributeError: ignored

*Why does this give an error?*

Name is an instance property (notice it is initialized as self.name as a property of the self object). It only exists for object or instances of this class. What is self ? It is reference to an object/instance belonging to that class 

### Creating instances/objects of a class

In [87]:
kriti=TeamSaathiMembers("Kriti", "Kathmandu","Computer Engineering")
utsabi=TeamSaathiMembers("Utsabi", "Kathmandu","CSIT")

In [88]:
kriti.name

'Kriti'

In [78]:
utsabi.specialization

'CSIT'

Objects are mutable i.e attribute values can be changed dynamically. Let's change utsabi's specialization


In [79]:
utsabi.specialization='Computer Science & Information Technology'
utsabi.specialization

'Computer Science & Information Technology'

Creating functions within a class

In [90]:
class TeamSaathiMembers:
  project = "Project Saathi"
  def __init__(self, name, city,specialization):
    self.name = name
    self.city = city
    self.specialization = specialization
  
  def description(self): #this is an instance function
    return f"{self.name} is studying {self.specialization}"

  def alternative_description():
    pass

In [93]:
TeamSaathiMembers.description

<function __main__.TeamSaathiMembers.description>

In [94]:
arsana=TeamSaathiMembers("Arsana", "Kathmandu","Bsc. Computing")
arsana.description()

'Arsana is studying Bsc. Computing'

### Class Inheritance

In [106]:
class TeamSaathiMentors(TeamSaathiMembers):
  def __init__(self,name,location,specialization,task):
    super().__init__(name,location,specialization)
    self.task=task
  
  def description(self): 
    print(f"Mentor {self.name} is responsible for the {self.task}")

In [107]:
rijesh = TeamSaathiMentors ("Rijesh","Munich","Computer Science","Python Workshop")
rijesh.description()

Mentor Rijesh is responsible for the Python Workshop


#### Super()

In [109]:
class TeamSaathiMentors(TeamSaathiMembers):
  def __init__(self,name,location,specialization,task):
    super().__init__(name,location,specialization)
    self.task=task
  
  def description(self):
    print(super().description())
    print(f"Mentor {self.name} is responsible for the {self.task}")

In [110]:
rijesh = TeamSaathiMentors ("Rijesh","Munich","Computer Science","Python Workshop")
rijesh.description()

Rijesh is studying Computer Science
Mentor Rijesh is responsible for the Python Workshop


### Summary : Structure of a Class in Python

In [41]:
class ClassName:
  class_property_1 = "I am a property of class ClassName"
  class_property_2 = "I am a property of class ClassName"
  def __init__(self,object_property1,object_property2):
    '''
    I am the __init__ function. 
    I initialize new objects of this class and my main job is to take in whatever properties you feed me with and store it in self. 
    Without me no new objects can be created from this class !
    '''
    self.object_property1 = "I am a property of the initialized object"
    self.object_property2 = "I am a property of the initialized object"

**Exercise**: Methods surrounded with double underscores like \_\_init\_\_ are called **dunder methods or magic methods**. They are an integral part of OOP in python. Get a better understanding with this tutorial: https://www.geeksforgeeks.org/dunder-magic-methods-python

# Demo: Structuring a python project
See the project structure here https://github.com/sheetalgiri/python-workshop-2021-day-2 

You will notice \_\_init_\_.py files in each folder. The \_\_init_\_.py files are required to make Python treat directories containing the file as packages. This prevents directories with a common name, such as string, unintentionally hiding valid modules that occur later on the module search path. In the simplest case, \_\_init\_\_.py can just be an empty file, but it can also execute initialization code for the package or set the \_\_all_\_ variable. 
(Source : https://docs.python.org/3/tutorial/modules.html)

#The Assert Keyword
If the defined condition returns False, AssertionError is raised:

In [112]:
teamname = input("Enter team name: ")
assert teamname == "Project Saathi", "Team Name should be Project Saathi"


Enter team name: Project Saathi


#Unit testing

Unit testing is a level of software testing where individual units / components of a software checked to verify correct functionality. They are tremendously useful because they help:

*   Find software bugs early
*   Ensure that the code does what is supposed to do
*   Help debug our code
*   Simplify the refactoring/code restructuring process
*   Speed up the integration process

There are different testing frameworks available for Python. Here we will use the UnitTest Framework which comes with the python package by default( https://docs.python.org/3/library/unittest.html)


### Simple test function

In [114]:
def test_sum():
    assert sum([1, 2, 3]) == 6, "Error ! Should be 6"

test_sum()

What is https://stackoverflow.com/questions/419163/what-does-if-name-main-do

### Demo: Calculator Testing (based on [source](https://github.com/AndyLPK247/python-testing-101))

more assert functions here: https://docs.python.org/3/library/unittest.html

# Numpy Basics

In [115]:
import numpy as np

### Creating an array

In [116]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

### Dimensionality

In [117]:
print(arr.ndim)

1


In [118]:
two_dimensional_arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [119]:
print(two_dimensional_arr.ndim)

2


In [121]:
two_dimensional_arr.shape

(2, 5)

## Array Indexing

In [127]:
arr=np.array([1,2,3,4,5])

First element of *arr* (Note that the indexing starts from 0)

In [123]:
arr[0]

1

Last element of *arr*

In [126]:
arr[-1]

5

Indexing in n-dimension arrays

In [128]:
twodim_arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(twodim_arr[0,1]) #2nd element
print(twodim_arr[0,4]) #5th element

2
5


In [132]:
twodim_arr[0,1]

2

In [129]:
threedim_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Shape of threedim_arr:",threedim_arr.shape)
print(threedim_arr)

Shape of threedim_arr: (2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


How do we select 6 ?

In [ ]:
threedim_arr[0, 1, 2]

###Array slicing
arr[start:end:step]

In [134]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [137]:
print("Return every other element in the array",arr[::2])
print("Returns elements from index 4 to the ened of the array",print(arr[4:]))

Return every other element in the array [1 3 5 7]
[5 6 7]
Returns elements from index 4 to the ened of the array None


### Calculation functions of numpy arrays

In [ ]:
np.sum([[0, 1], [0, 5]])

In [ ]:
np.sum([[0, 1], [0, 5]], axis=0)

In [ ]:
np.sum([[0, 1], [0, 5]], axis=1)

In [140]:
arr= np.array([[10, 11, 12],[13, 14, 15]])
arr

5

In [141]:

np.argmax(arr)

5

**Exercise** Explore more calculation functions https://numpy.org/doc/stable/reference/arrays.ndarray.html#calculation 

**Exercise** Create a python notebook and go through the examples in https://numpy.org/doc/stable/reference/arrays.indexing.html . You only have to cover "Basic Slicing and Indexing" and "Advanced Indexing"